### PR TITLE
Add classes to import budget lines from files with new CSV format

### PR DESCRIPTION
**Pull request by entantoencuanto**
This PR adds a class which can handle a CSV with the format described in PopulateTools/issues#1346 transforming their values in a JSON suitable for uploading in with elasticsearch

### CODE REVIEW

**Comment by ferblape** [comment]
@entantoencuanto code looks good, but in order to test it in staging, could you add a rake task to Gobierto that calls this class? The single argument of the rake task should be the CSV file path, as the rest of information is autocontained in the data sheet.

**Comment by furilo** [comment]
We'd need to define the target site inside the Gobierto installation?

**Comment by entantoencuanto** [comment]
For budget lines there is no need to define a target side because all elastic data is shared
For custom categories the task must specify the destination site

**Comment by ferblape** [comment]
True, then pass the site as argument, for example the host of the site.

**Comment by entantoencuanto** [comment]
Added to gobierto staging the following tasks:

For importing budget lines:
```
rails gobierto_budgets:data:import_gobierto_budgets_data[csv_path]
```
The example file may raise errors calling the task if the code contains non numerical chars.

For importing custom categories:
```
rails gobierto_budgets:custom_categories:import_gobierto_budgets_data[site_domain,csv_path]
```

**Comment by ferblape** [comment]
Something is not working with `econmic-functional` budget lines, see the example CSV I'm using: 
[full_economic_functional.csv](https://github.com/PopulateTools/gobierto_data/files/7230733/full_economic_functional.csv). This example uses the site cortegada.gobierto.test, available in the seeds.

If you see the economic-functional rows:

Screenshot 2021-09-26 at 06 51 20

When I visit functional budget line 13 or functional budget line 22 I'd expect to see the economic budget line 1, but right now is empty. Could you investigate it?

**Pull request merged**
